### ISSUE TITLE
Timer failed under python 2.6

### ISSUE THREAD

**Issue by terminatorzwm** [WoLpH/python-progressbar#126]
#### Description

Timer widget failed under python 2.6 with:
Traceback (most recent call last):
  File "./pzdiff.py", line 207, in main
    pzdiff(path1, path2)
  File "./pzdiff.py", line 71, in pzdiff
    ProgressManager().setup(settings.PROGRESS)
  File "/srv/zwm/pzdiff/utils/progress.py", line 30, in setup
    self.register(ProgressBar())
  File "/srv/zwm/pzdiff/utils/progress.py", line 98, in __init__
    self.bar.start()
  File "/srv/zwm/pzdiff/libs/progressbar/bar.py", line 583, in start
    self.update(self.min_value, force=True)
  File "/srv/zwm/pzdiff/libs/progressbar/bar.py", line 539, in update
    StdRedirectMixin.update(self, value=value)
  File "/srv/zwm/pzdiff/libs/progressbar/bar.py", line 129, in update
    DefaultFdMixin.update(self, value=value)
  File "/srv/zwm/pzdiff/libs/progressbar/bar.py", line 59, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "/srv/zwm/pzdiff/libs/progressbar/bar.py", line 470, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "/srv/zwm/pzdiff/libs/progressbar/bar.py", line 445, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "/srv/zwm/pzdiff/libs/progressbar/widgets.py", line 204, in __call__
    return FormatWidgetMixin.__call__(self, progress, data, **kwargs)
  File "/srv/zwm/pzdiff/libs/progressbar/widgets.py", line 73, in __call__
    return (format or self.format) % data
KeyError: u'elapsed'
------------------------------------------------------------------------------
The reason is format_time() in utils module throws:
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

#### Code

Run Timer widget under python 2.6

#### Versions

- Python version: 2.6.6
- Operating System: Linux
- Package version: 2-3.20.2

**Comment by WoLpH** [comment]
Unfortunately Python 2.6 has become quite difficult to maintain, many of the libraries we use for testing have dropped Python 2.6 support making it impossible for me to test.

For what it's worth, version 3.6.x should still function on Python 2.6 so you can try that.

```
pip install 'progressbar2<3.7.0'
```
