### ISSUE TITLE
How to get Days in ETA to just show in hours?

### ISSUE THREAD

**Issue by p1r473** [WoLpH/python-progressbar#198]
Hello,
I am trying to put a progress bar with an ETA, but instead of  Days, HH:MM:SS, I just want to show HHH:MM:SS
How can I do this?

**Comment by WoLpH** [comment]
There's no built-in solution to take care of that, but it's easy enough to create a custom widget

```python
import time
import progressbar
from datetime import timedelta


class CustomETA(progressbar.widgets.ETA):

    def __call__(self, progress, data):
        # Run `ETA.__call__` to update `data`
        progressbar.widgets.ETA.__call__(self, progress, data)

        # ETA might not be available, if the maximum length is not available
        # for example
        if data.get('eta_seconds'):
            # By using divmod we can split the timedelta to hours and the
            # remaining timedelta
            hours, delta = divmod(
                timedelta(seconds=data['eta_seconds']),
                timedelta(hours=1),
            )
            return '{hours}{minutes_truncated}'.format(
                hours=hours,
                # Strip the 0 hours from the timedelta
                delta_truncated=str(delta).lstrip('0'),
            )
        else:
            return '-' * 8


widgets = [
    progressbar.Percentage(),
    ' :: ',
    progressbar.Bar(),
    ' :: ',
    CustomETA(),
]
bar = progressbar.ProgressBar(widgets=widgets)
for i in bar(range(1000000)):
    time.sleep(0.1)
```

**Comment by p1r473** [comment]
How do I pass eta_seconds to it?
Getting the error eta_seconds is undefined

My implementation is:
bar = progressbar.ProgressBar(max_value=len(paths),widgets=[format_custom_text,
                CustomETA(format_not_started='%(value)2d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format_finished='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s|ETA:%(eta)8s', format_zero='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format_NA='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s'),
                progressbar.Bar(marker='#', left='|', right='|', fill=' ', fill_left=True),               
                ])

I am crashing on the update:
bar.update(progressCounter)

**Comment by p1r473** [comment]
How do I pass eta_seconds to it?
Getting the error timedelta is undefined

My implementation is:
```python
format_custom_text = progressbar.FormatCustomText(
                '%(f)s',
                dict(
                    f='',
                )
            )
            bar = progressbar.ProgressBar(max_value=len(paths),widgets=[format_custom_text,
                CustomETA(format_not_started='%(value)2d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format_finished='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s|ETA:%(eta)8s', format_zero='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format_NA='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s'),
                progressbar.Bar(marker='#', left='|', right='|', fill=' ', fill_left=True),               
                ])
```

I am crashing on the update:
bar.update(progressCounter)

**Comment by WoLpH** [comment]
The example above is a fully working one. That's how you can call the `ETA.__call__` from your own `__call__` method. 

As for the `timedelta`, I think you've forgot to copy the `import` in that case.

**Comment by p1r473** [comment]
Sorry, I must be doing something wrong:

```python
Traceback (most recent call last):
  File "bitrot.py", line 1606, in <module>
    run_from_command_line()
  File "bitrot.py", line 1600, in run_from_command_line
    bt.run()
  File "bitrot.py", line 737, in run
    bar.update(progressCounter)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 552, in update
    self.start()
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 658, in start
    self.update(self.min_value, force=True)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 591, in update
    StdRedirectMixin.update(self, value=value)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 146, in update
    DefaultFdMixin.update(self, value=value)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 68, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 517, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 492, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "bitrot.py", line 592, in __call__
    delta_truncated=str(delta).lstrip('0'),
KeyError: 'minutes_truncated'
--------|#############################################################################################################|
```
```python
Hashing all files... Please wait...
Traceback (most recent call last):
  File "bitrot.py", line 1606, in <module>
    run_from_command_line()
  File "bitrot.py", line 1600, in run_from_command_line
    bt.run()
  File "bitrot.py", line 737, in run
    bar.update(progressCounter)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 552, in update
    self.start()
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 658, in start
    self.update(self.min_value, force=True)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 591, in update
    StdRedirectMixin.update(self, value=value)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 146, in update
    DefaultFdMixin.update(self, value=value)
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 68, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 517, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "c:\Python3\lib\site-packages\progressbar\bar.py", line 492, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "bitrot.py", line 590, in __call__
    hours=hours,
KeyError: 'minutes_truncated'
--------|
```

**Comment by WoLpH** [comment]
Sorry about that, I changed `minutes_truncated` to `delta_truncated` which broke the example. I've fixed it now

**Comment by WoLpH** [comment]
As for the call, a simple `bar. update(some_counter) `  will work just fine

**Comment by p1r473** [comment]
Thanks!
So it runs now, but I think the above class now longer works with the old formatting:
```python
CustomETA(format_not_started='%(value)2d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format_finished='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s|ETA:%(eta)8s', format_zero='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s', format_NA='%(value)01d/%(max_value)d|%(percentage)3d%%|Elapsed:%(elapsed)8s'),

```

Is there a way I can get my old output to work, but the only difference being that the ETA just doesn't show the days (just HHH)? It doesn't show time elapsed, or percentage, or even ETA anymore.

**Comment by WoLpH** [comment]
This is about as close as it gets without copying `ETA.__call__` or monkeypatching `utils.format_time()`:

(untested)
```python

import time
import progressbar
from datetime import timedelta


class CustomETA(progressbar.widgets.ETA):

    def __call__(self, progress, data):
        # Run `ETA.__call__` to update `data`. This adds the `eta_seconds`
        formatted = progressbar.widgets.ETA.__call__(self, progress, data)

        # ETA might not be available, if the maximum length is not available
        # for example
        if data.get('eta'):
            # By using divmod we can split the timedelta to hours and the
            # remaining timedelta
            hours, delta = divmod(
                timedelta(seconds=data['eta_seconds']),
                timedelta(hours=1),
            )
            data['eta'] = '{hours}{delta_truncated}'.format(
                hours=hours,
                # Strip the 0 hours from the timedelta
                delta_truncated=str(delta).lstrip('0'),
            )
            return Timer.__call__(self, progress, data, format=self.format)
        else:
            return formatted


widgets = [
    progressbar.Percentage(),
    ' :: ',
    progressbar.Bar(),
    ' :: ',
    CustomETA(),
]
bar = progressbar.ProgressBar(widgets=widgets)
for i in bar(range(1000000)):
    time.sleep(0.1)

**Comment by p1r473** [comment]
What's that Timer class? Its undefined.
return Timer.__call__(self, progress, data, format=self.format)
Sorry for all the help requests!

**Comment by WoLpH** [comment]
That's from the widgets module, so this instead would work: `progressbar.widgets.Timer`

**Comment by p1r473** [comment]
Thank you so much! It works.
I made one change:
```python
timedelta(seconds=int(data['eta_seconds'])),
```
The seconds were showing decimal places, so I casted them as an int.

I don't have any files big enough here at work to test the multiple days thing, bit I'll report back tonight and close the issue if it works.
Thanks again.

**Comment by WoLpH** [comment]
That's probably the easiest method to truncate the seconds :)
You could make it slightly smarter by only truncating if you have more than a minute to go or something. But it depends on your use case.
