### ISSUE TITLE
"Sleeping" Timer

### ISSUE THREAD

**Issue by mikkelee** [WoLpH/python-progressbar#218]
I'm trying to build a timer/bar that will sleep a specified amount after updating the progressbar but I'm hitting a wall.

I can't seem to access the variables, I must be misunderstanding the documentation.

This is what I have (I'm aware that the sleep is before the super call, I can always polish when I know how to access the variables):

```python
import progressbar

class SleepTimer(progressbar.Timer):
	def __init__(self, **kwargs):
		super().__init__(**kwargs, format='Sleep: %(variables.sleep_seconds)s')

	def __call__(self, progress, data):
		time.sleep(data['variables'].get('sleep_seconds', 0))
		return super().__call__(progress, data)

items = [1,2,3]

bar = progressbar.ProgressBar(
	widgets = [
		progressbar.Percentage(),
		' ', progressbar.Bar(),
		' ', progressbar.Timer(),
		' ', progressbar.AbsoluteETA(),
		' ', SleepTimer(),
	],
	variables={'sleep_seconds': 0}
)
for item in bar(items):
	bar.update(sleep_seconds=5)
```

It throws on trying to access the variables:

```console
Error while formatting 'Sleep: %(variables.sleep_seconds)s'                                                                                                            
{'days_elapsed': 0.0,
 'dynamic_messages': {},
 'elapsed': '0:00:00',
 'end_time': None,
 'eta': '2020-01-18 15:15:37',
 'eta_seconds': datetime.datetime(2020, 1, 18, 15, 15, 37, 102043),
 'finished': None,
 'hours_elapsed': 0.0,
 'last_update': datetime.datetime(2020, 1, 18, 15, 8, 43, 101946),
 'last_update_time': datetime.datetime(2020, 1, 18, 15, 8, 43, 101946),
 'max': 3,
 'max_value': 3,
 'minutes_elapsed': 0.0,
 'percentage': 0.0,
 'previous_value': 0,
 'seconds': 0.000138,
 'seconds_elapsed': 0.000138,
 'start': datetime.datetime(2020, 1, 18, 15, 8, 43, 101808),
 'start_time': datetime.datetime(2020, 1, 18, 15, 8, 43, 101808),
 'time_elapsed': datetime.timedelta(microseconds=138),
 'total_seconds_elapsed': 0.000138,
 'updates': 1,
 'value': 0}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 455, in __next__
    self.start()
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 656, in start
    self.update(self.min_value, force=True)
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 589, in update
    StdRedirectMixin.update(self, value=value)
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 146, in update
    DefaultFdMixin.update(self, value=value)
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 68, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 517, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "/usr/local/lib/python3.7/site-packages/progressbar/bar.py", line 492, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "/usr/local/lib/python3.7/site-packages/progressbar/widgets.py", line 213, in __call__
    return FormatWidgetMixin.__call__(self, progress, data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/progressbar/widgets.py", line 78, in __call__
    return (format or self.format) % data
KeyError: 'variables.sleep_seconds'
```

**Comment by WoLpH** [comment]
You can look at this example. That should be close to what you need:
https://github.com/WoLpH/python-progressbar/blob/01780dc76efb2a5d3108555098ca9a73c6b10de3/examples.py#L531-L549

**Comment by mikkelee** [comment]
Excellent! Many thanks :)

This seems to work as intended:

```python
import random
import time
import progressbar

class SleepingBar(progressbar.bar.ProgressBar):
	def default_widgets(self):
		return super().default_widgets() + [' ', progressbar.widgets.Variable('Sleep', width=4, precision=2)]
	def update(self, *args, **kwargs):
		super().update(*args, **kwargs)
		time.sleep(self.variables.get('Sleep', 0.0))

items = [1,2,3]

bar = SleepingBar(
	variables={'Sleep': 0.0}
)

for item in bar(items):
	bar.update(Sleep=random.uniform(1.0, 3.0))
```

**Comment by mikkelee** [comment]
A minor thing: Is it possible to separate the value class name from the variable string name?

ie. something like `return super().default_widgets() + [' ', progressbar.widgets.Variable('Sleep', format=f'Sleeping: {sleep_seconds:0.02f}')]` so I can `bar.update(sleep_seconds=n)`

**Comment by WoLpH** [comment]
Only if you inherit the `__call__` method and override that behivour:
https://github.com/WoLpH/python-progressbar/blob/01780dc76efb2a5d3108555098ca9a73c6b10de3/progressbar/widgets.py#L849-L882

This should give you the same result though:
```python
progressbar.widgets.Variable('sleep_seconds', format='Sleeping: {formatted_value}', precision=2)
```

**Comment by mikkelee** [comment]
Thanks for all the help, and good catch on the f! :D

**Comment by mikkelee** [comment]
I wanted to try having the sleeping `Variable` update, but it appears setting `self.variables['sleep_seconds']` doesn't get set like I expected it to.

I can tell that it does sleep and update the display via `super()` because `Elapsed time` updates once per second, but `sleep_seconds` never reaches zero so it simply keeps going (unless `sleep_seconds` starts out at 0).

```python
import time
import progressbar

class SleepingBar(progressbar.bar.ProgressBar):
	def default_widgets(self):
		return super().default_widgets() + [
			' ',
			progressbar.widgets.Variable(
				name='sleep_seconds',
				format='(Sleeping: {value:d}s)',
			)
		]

	def update(self, *args, **kwargs):
		super().update(*args, **kwargs)
		while self.variables['sleep_seconds'] > 0:
			self.variables['sleep_seconds'] -= 1
			time.sleep(1)
			super().update(*args, **kwargs)
		self.variables['sleep_seconds'] = 0

items = [0, 1, 10]

bar = SleepingBar(
	variables={'sleep_seconds': 0}
)

for item in bar(items):
	bar.update(sleep_seconds=item)
``

**Comment by WoLpH** [comment]
The problem is that you're updating `self.variables` directly. You should pass it to `update()` instead.

```python
import time
import progressbar

class SleepingBar(progressbar.bar.ProgressBar):
	def default_widgets(self):
		return super().default_widgets() + [
			' ',
			progressbar.widgets.Variable(
				name='sleep_seconds',
				format='(Sleeping: {value:d}s)',
			)
		]

	def update(self, *args, **kwargs):
		super().update(*args, **kwargs)
		while self.variables['sleep_seconds'] > 0:
			kwargs['sleep_seconds'] = self.variables['sleep_seconds'] - 1
			time.sleep(1)
			super().update(*args, **kwargs)

items = [0, 1, 10]

bar = SleepingBar(
	variables={'sleep_seconds': 0}
)

for item in bar(items):
	bar.update(sleep_seconds=item)
```

**Comment by mikkelee** [comment]
Aha, thank you again!
